version: '3'

services:

  gateway-service:
    build: ../gateway
    container_name: gateway-service
    ports:
      - '${GATE_WAY_PORT}:${GATE_WAY_PORT}'
    expose:
      - '${GATE_WAY_PORT}'

  front-end:
    build: ../frontend
    container_name: frontend
    ports:
      - '${FRONT_END_PORT}:80'
    expose:
      - '${FRONT_END_PORT}'


  univ-service-db:
    image: ${UNIV_SERVICE_DB_IMAGE_NAME}
    container_name: ${UNIV_SERVICE_DB_CONTAINER_NAME}
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "${UNIV_SERVICE_DB_PORT}:${UNIV_SERVICE_DB_PORT}"
    environment:
      - MYSQL_DATABASE=${UNIV_SERVICE_DB_NAME}
      - MYSQL_USER=${UNIV_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${UNIV_SERVICE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${UNIV_SERVICE_DB_PASSWORD_ROOT}

  univ-service-back:
    build: ${UNIV_SERVICE_PROJECT_PATH}
    container_name: ${UNIV_SERVICE_CONTAINER_NAME}
    image: ${UNIV_SERVICE_IMAGE_NAME}
    ports:
      - "${UNIV_SERVICE_BACK_PORT}:${UNIV_SERVICE_BACK_PORT}"
    environment:
      - UNIV_SERVICE_DB_URL=jdbc:mysql://univ-service-db:3306/${UNIV_SERVICE_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - UNIV_SERVICE_DB_USER=${UNIV_SERVICE_DB_USER}
      - UNIV_SERVICE_DB_PASSWORD=${UNIV_SERVICE_DB_PASSWORD}
    depends_on:
      - univ-service-db



volumes:
  app-data:

